let inAirLangData = {
  "inAir.itvResult.label.excellent": "탁월",
  "inAir.itvResult.label.good": "우수",
  "inAir.itvResult.label.normal_high": "보통 상",
  "inAir.itvResult.label.normal": "보통",
  "inAir.itvResult.label.normal_low": "보통 하",
  "inAir.itvResult.label.bad": "미흡",
  "inAir.itvResult.label.so_bad": "매우미흡",
  "inAir.itvResult.error.msg1": "인자 갯수가 안맞네용",
  "inAir.itvResult.label.available": "가능",
  "inAir.itvResult.label.proxy_doubt": "대리시험 의심",
  "inAir.itvResult.label.doubt": "의심",
  "inAir.itvResult.label.unavailable": "불가",
  "inAir.itvResult.error.msg2": "영상을 재생할수 없는 환경입니다.<br> Microsoft Edge, Google Chrome, Firefox 등 <br> 데스크탑PC에서 재생이 가능합니다.",
  "inAir.itvResult.error.msg3": "현재 브라우저에서 영상을 재생 할 수 없습니다.",
  "inAir.itvResult.label.basic_question": "기본 질문",
  "inAir.itvResult.label.situation_question": "상황 질문",
  "inAir.itvResult.label.struct_question": "심층/구조화 질문",
  "inAir.itvResult.label.customizing": "커스터마이징",
  "inAir.itvResult.label.no_clip": "[영상x]",
  "inAir.itvResult.label.no_question": "질문 내용이 없습니다.",
  "inAir.itvResult.label.no_clip2": "영상이 없네요.",
  "inAir.itvResult.label.screening": "전 형 명",
  "inAir.itvResult.label.exam": "검 사 명",
  "inAir.itvResult.label.interest_discipline": "지원 분야",
  "inAir.itvResult.label.work_department": "재직부서",
  "inAir.itvResult.label.cellphone": "핸 드 폰",
  "inAir.itvResult.label.email": "이 메 일",
  "inAir.itvResult.label.overall_rating": "종합평가",
  "inAir.itvResult.guide.msg1": "종합평가 결과는<br>공개하지 않습니다",
  "inAir.itvResult.label.score": "점",
  "inAir.itvResult.label.rank": "등",
  "inAir.itvResult.label.people": "명",
  "inAir.itvResult.label.rating": "상위(%)",
  "inAir.itvResult.label.trust_available": "응답신뢰가능",
  "inAir.itvResult.label.check_clip": "영상확인필요",
  "inAir.itvResult.label.trust_unavailable": "응답신뢰불가",
  "inAir.itvResult.guide.msg2": "OO님은 정상적으로 온라인 면접을 완료하였으며, 분석 결과는 신뢰할 수 있습니다.",
  "inAir.itvResult.guide.msg3": "OO님은 정상적으로 온라인 면접을 완료하였으며, 분석 결과는 신뢰할 수 있습니다. 다만, 영상을 분석한 결과 원활하지 못한 응시가 예상되는 부분이 있으니 실제 영상을 확인하시기 바랍니다.",
  "inAir.itvResult.guide.msg4": "음성 또는 영상 데이터가 불안정하여 정상적으로 분석할 수 없습니다. 노란색 표기가 붙은 영상을 확인해 보시기 바랍니다.",
  "inAir.itvResult.label.confirm": "확인",
  "inAir.itvResult.label.support": "지원",
  "inAir.itvResult.label.field": "현직",
  "inAir.itvResult.label.job_fitt": "직군적합",
  "inAir.itvResult.setKeyword.dull": "감정에둔한",
  "inAir.itvResult.setKeyword.clumsy": "감정전달 서툰",
  "inAir.itvResult.setKeyword.need_check": "검증이 필요한",
  "inAir.itvResult.setKeyword.result_oriented": "결과중심적인",
  "inAir.itvResult.setKeyword.planner": "계획적인",
  "inAir.itvResult.setKeyword.lead_sympathy": "공감을 이끄는",
  "inAir.itvResult.setKeyword.sympathy": "공감을 하는",
  "inAir.itvResult.setKeyword.fair": "공정한",
  "inAir.itvResult.setKeyword.ruin_rule": "규칙을 어기는",
  "inAir.itvResult.setKeyword.follow_rule": "규칙을 지키는",
  "inAir.itvResult.setKeyword.rgular": "규칙적인",
  "inAir.itvResult.setKeyword.positive": "긍정적인",
  "inAir.itvResult.setKeyword.well_remeber": "기억력이 좋은",
  "inAir.itvResult.setKeyword.no_tenacity": "끈기가 없는",
  "inAir.itvResult.setKeyword.illogical": "논리가 부족한",
  "inAir.itvResult.setKeyword.logical": "논리적인",
  "inAir.itvResult.setKeyword.active": "능동적인",
  "inAir.itvResult.setKeyword.careless": "덤벙거리는",
  "inAir.itvResult.setKeyword.slow_speecher": "말이 느린",
  "inAir.itvResult.setKeyword.fast_speecher": "말이 빠른",
  "inAir.itvResult.setKeyword.charming": "매력있는",
  "inAir.itvResult.setKeyword.considerate": "배려하는",
  "inAir.itvResult.setKeyword.murmur": "버벅거리는",
  "inAir.itvResult.setKeyword.normal": "보통 수준의",
  "inAir.itvResult.setKeyword.diligent": "부지런한",
  "inAir.itvResult.setKeyword.discreet": "분별 있는",
  "inAir.itvResult.setKeyword.analytical": "분석적인",
  "inAir.itvResult.setKeyword.unsatisfactory": "불만족하는",
  "inAir.itvResult.setKeyword.critical": "비난하는",
  "inAir.itvResult.setKeyword.scatterbrained": "산만한",
  "inAir.itvResult.setKeyword.unconvincing": "설득력 없는",
  "inAir.itvResult.setKeyword.persuasive": "설득력 있는",
  "inAir.itvResult.setKeyword.obstinate": "악착같은",
  "inAir.itvResult.setKeyword.self_contentment": "안분지족하는",
  "inAir.itvResult.setKeyword.Stable": "안정적인",
  "inAir.itvResult.setKeyword.ambitious": "야망있는",
  "inAir.itvResult.setKeyword.sensitive": "예민한",
  "inAir.itvResult.setKeyword.unsuspecting": "의심하지않는",
  "inAir.itvResult.setKeyword.resolute": "의연한",
  "inAir.itvResult.setKeyword.selfish": "이기적인",
  "inAir.itvResult.setKeyword.understanding": "이해심많은",
  "inAir.itvResult.setKeyword.handsome": "인상이 좋은",
  "inAir.itvResult.setKeyword.spontaneous": "자발적인",
  "inAir.itvResult.setKeyword.confident": "자신감 있는",
  "inAir.itvResult.setKeyword.quick_witted": "잘 알아채는",
  "inAir.itvResult.setKeyword.communicative": "전달력 있는",
  "inAir.itvResult.setKeyword.blame": "주변을 탓하는",
  "inAir.itvResult.setKeyword.attentive": "주의력이 좋은",
  "inAir.itvResult.setKeyword.off_the_bat": "즉흥적인",
  "inAir.itvResult.setKeyword.focused": "집중하는",
  "inAir.itvResult.setKeyword.slow_at_work": "처리가 느린",
  "inAir.itvResult.setKeyword.fast_at_work": "처리가 빠른",
  "inAir.itvResult.setKeyword.systematic": "체계적인",
  "inAir.itvResult.setKeyword.nothing_special": "특징없는",
  "inAir.itvResult.setKeyword.ordinary": "평범한",
  "inAir.itvResult.setKeyword.not_give_up": "포기하지 않는",
  "inAir.itvResult.setKeyword.bright_face": "표정이 밝은",
  "inAir.itvResult.setKeyword.appealing": "호소력있는",
  "inAir.itvResult.setKeyword.free_from_anger": "화내지않는",
  "inAir.itvResult.label.applicant_keyword": "지원자 키워드",
  "inAir.itvResult.label.core_keyword": "핵심 키워드",
  "inAir.itvResult.label.member": "재직자",
  "inAir.itvResult.label.applicant": "지원자",
  "inAir.itvResult.label.entire": "전체",
  "inAir.itvResult.label.job_group": "직군",
  "inAir.itvResult.label.rating_rank": "수/등수 (상위%)",
  "inAir.itvResult.label.average": "평균",
  "inAir.itvResult.label.score2": "점수",
  "inAir.itvResult.label.total_score": "종합점수(점)",
  "inAir.itvResult.label.number_of_applicant": "인원수(명)",
  "inAir.itvResult.label.average_score": "평균 O점",
  "inAir.itvResult.label.top_rank": "상위 OO%",
  "inAir.itvResult.label.entire_score": "전체 O점수",
  "inAir.itvResult.label.job_score": "직군 O점수",
  "inAir.itvResult.label.conclusion_comment": "종합코멘트",
  "inAir.itvResult.guide.msg5": "의 응시 결과를 신뢰할 수 없습니다.",
  "inAir.itvResult.guide.msg6":"OO님의 결과는 다른 재직자와 비교할 수 없습니다.<br><br>따라서 본 결과를 의사 결정에 활용하는 것은 적절하지 않습니다.<br><br>응답신뢰불가 원인에 해당하는 키워드를 확인하시기 바랍니다.",
  "inAir.itvResult.guide.msg7": "OO님의 결과는 다른 지원자와 비교할 수 없습니다.",
  "inAir.itvResult.guide.msg8":"OO님의 결과는 다른 지원자와 비교할 수 없습니다.<br><br>따라서 본 결과를 의사 결정에 활용하는 것은 적절하지 않습니다.<br><br>응답신뢰불가 원인에 해당하는 키워드를 확인하시기 바랍니다.",
  "inAir.itvResult.label.chart_title": "역량 점수 종합 다이어그램",
  "inAir.itvResult.label.order_capability": "역량순",
  "inAir.itvResult.label.order_low": "낮은순",
  "inAir.itvResult.label.order_high": "높은순",
  "inAir.itvResult.label.trust": "신뢰",
  "inAir.itvResult.label.value": "가치",
  "inAir.itvResult.label.passion": "열정",
  "inAir.itvResult.label.strategy": "전략",
  "inAir.itvResult.label.relation": "관계",
  "inAir.itvResult.label.organization_suitability": "조직적합",
  "inAir.itvResult.label.impression": "호감도",
  "inAir.itvResult.guide.msg9": "팝업 차단을 해제해 주세요",
  "inAir.itvResult.label.detail_job": "직군/직무적합도(상세)",
  "inAir.itvResult.label.job": "직무",
  "inAir.itvResult.label.strength": "강점",
  "inAir.itvResult.label.weakness": "약점",
  "inAir.itvResult.label.strength_weakness": "강·약점 요인 분포",
  "inAir.itvResult.label.performance_checkList": "성과역량지수 검증항목",
  "inAir.itvResult.label.relationship_checkList": "관계역량&조직적합지수 검증항목",
  "inAir.itvResult.label.verification_content": "검증내용",
  "inAir.itvResult.label.strength_factor": "강점 요인",
  "inAir.itvResult.label.weakness_factor": "약점 요인",
  "inAir.itvResult.guide.msg10": "OO중 검증이 필요한 요인은 OO",
  "inAir.itvResult.guide.msg11": "입니다",
  "inAir.itvResult.label.individual": "개인정보영역",
  "inAir.itvResult.label.reliability": "신뢰가능성",
  "inAir.itvResult.label.applicant_keyword2": "지원자키워드",
  "inAir.itvResult.label.factor_definition": "지수 및 요인별 정의",
  "inAir.itvResult.guide.msg12": "지원자의 역량을 바탕으로 검증에 필요한 질문과 실제 지원자의 응답 결과를 제공합니다.",
  "inAir.itvResult.label.interview_guide": "면접 질문 가이드",
  "inAir.itvResult.label.performance_score": "성과역량지수",
  "inAir.itvResult.label.relation_jobfit": "관계역량 & 조직적합지수",
  "inAir.itvResultV2.guide.msg1": "팝업 차단을 해제해 주세요",
  "inAir.itvResultV2.guide.msg2": "응시자 점수 분포가<br>블라인드 되었습니다.",
  "inAir.itvResultV2.guide.msg3": "전형 내 응시자 역량비교가<br>블라인드 되었습니다.",
  "inAir.itvResultV2.label.total_performance_score": "전체 역량 점수",
  "inAir.itvResultV2.label.low": "낮음",
  "inAir.itvResultV2.label.middle": "중간",
  "inAir.itvResultV2.label.high": "높음",
  "inAir.itvResultV2.label.decision_type": "의사결정 유형",
  "inAir.itvResultV2.label.field": "분야",
  "inAir.itvResultV2.guide.msg4": "의사결정 과정에서 나타나는 응시자의 행동 양식을 확인할 수 있습니다.",
  "inAir.itvResultV2.label.information_type": "정보 활용 유형",
  "inAir.itvResultV2.guide.msg5": "의사결정 과정에서 응시자가 주로 활용하는<br> 정보 유형을 확인할 수 있습니다.",
  "inAir.itvResultV2.label.normal": "보통",
  "inAir.itvResultV2.label.concentration_pattern": "집중력 변화 패턴",
  "inAir.itvResultV2.guide.msg6": "* 문항에 대한 누적 정답률과 응답시간의 변화 추이를 통해 응시자의 집중력을 확인 할 수 있습니다",
  "inAir.itvResultV2.label.accumulate_answer_rate": "누적 정답률(응시자)",
  "inAir.itvResultV2.label.accumulate_answer_rate2": "누적 정답률(규준)",
  "inAir.itvResultV2.label.response_time": "응답시간(응시자)",
  "inAir.itvResultV2.label.response_time2": "응답시간(규준)",
  "inAir.itvResultV2.label.question_number": "문항번호",
  "inAir.itvResultV2.label.concentration_profile": "집중력 프로파일",
  "inAir.itvResultV2.label.fulfillment": "수행",
  "inAir.itvResultV2.label.speed": "속도",
  "inAir.itvResultV2.label.good": "우수",
  "inAir.itvResultV2.label.bad": "미흡",
  "inAir.itvResultV2.label.beginning": "초반",
  "inAir.itvResultV2.label.middle2": "중반",
  "inAir.itvResultV2.label.last": "후반",
  "inAir.itvResultV2.label.difficulty_pattern": "난이도 적응 패턴",
  "inAir.itvResultV2.guide.msg7": "난이도에 따른 누적 정답률 변화 추이를 통해 응시자의 적응력 변화를 확인 할 수 있습니다.",
  "inAir.itvResultV2.label.accumulate_answer_rate3": "누적정답률",
  "inAir.itvResultV2.label.easy_type1": "쉬운 유형(응시자)",
  "inAir.itvResultV2.label.difficult_type1": "어려운 유형(응시자)",
  "inAir.itvResultV2.label.difficult_type2": "어려운 유형(규준)",
  "inAir.itvResultV2.label.easy_type2": "쉬운 유형(규준)",
  "inAir.itvResultV2.label.adaptive ability": "적응력 변화",
  "inAir.itvResultV2.label.easy_type3": "쉬운 유형",
  "inAir.itvResultV2.guide.msg8": "쉬운 유형에서 후반부로 갈수록 문제 풀이에 적응하는 수준을  의미합니다.",
  "inAir.itvResultV2.label.difficult_type3": "어려운 유형",
  "inAir.itvResultV2.guide.msg9": "어려운 유형에서 후반부로 갈수록 문제 풀이에 적응하는 수준을 의미합니다.",
  "inAir.itvResultV2.label.difficulty_up": "난이도 상승",
  "inAir.itvResultV2.guide.msg10":"동일한 게임 내에서 쉬운 유형에서 어려운 유형으로 난이도 변화가 있을 때 문제 풀이에 적응하는 수준을 의미합니다.",
  "inAir.itvResultV2.label.detail_job": "직군/직무적합도 (상세)",
  "inAir.itvResultV2.label.job": "직군",
  "inAir.itvResultV2.label.job_group": "직무",
  "inAir.itvResultV2.label.score": "점",
  "inAir.itvResultV2.label.blind": "블라인드",
  "inAir.itvResultV2.label.rank_summary": "{0}등/{1}명(상위 {2}%)",
  "inAir.itvResultV2.label.rank": "등",
  "inAir.itvResultV2.label.people": "명",
  "inAir.itvResultV2.label.top_rating": "(상위 {0}%)",
  "inAir.itvResultV2.label.division": "구분",
  "inAir.itvResultV2.label.detail_list": "세부항목",
  "inAir.itvResultV2.label.no_compare_score": "비교 점수 없음",
  "inAir.itvResultV2.label.total_average": "전형 전체 평균",
  "inAir.itvResultV2.label.jobgroup_average": "지원 직군 평균",
  "inAir.itvResultV2.label.representative_list": "대표 구성원",
  "inAir.itvResultV2.label.skill_definition": "역량 정의",
  "inAir.itvResultV2.label.decision_type_guide": "의사결정 유형별 질문 가이드",
  "inAir.itvResultV2.label.recommend_question": "추천 질문",
  "inAir.itvResultV2.label.interview_question": "면접 질문 가이드",
  "inAir.itvResultV2.label.weakness": "약점",
  "inAir.itvResultV2.label.strength": "강점",
  "inAir.itvResultV2.label.need_valid": "검증필요",
  "inAir.itvResultV2.label.apply_for_field": "지원 분야",
  "inAir.itvResultV2.label.apply_for_job": "지원직군",
  "inAir.itvResultV2.label.screening": "전형",
  "inAir.itvResultV2.guide.msg11":"응시자의 응시 결과를 신뢰할 수 없습니다.<br> {0}님의 결과를 다른 응시자와 비교할 수 없어, 본 결과를 의사 결정에 활용하는 것은 적절하지 않습니다.<br>응답신뢰불가 원인에 해당하는 키워드를 확인하시기 바랍니다.",
  "inAir.itvResultV2.label.applicant_skill": "응시자 역량 해석",
  "inAir.itvResultV2.comment.msg1": "{0}이<br>블라인드 되었습니다.",
  "inAir.itvResultV2.label.entire": "전체",
  "inAir.itvResultV2.label.applicant": "지원",
  "inAir.itvResultV2.label.examinee_score_scatter": "응시자 점수 분포",
  "inAir.itvResultV2.label.score_and_top": "점/상위",
  "inAir.itvResultV2.label.people_number": "인원수(명)",
  "inAir.itvResultV2.label.score3": "점수 (점)",
  "inAir.itvResultV2.label.average_score": "평균 {0}점",
  "inAir.itvResultV2.label.rank_blind": "등수 블라인드",
  "inAir.itvResultV2.label.summary_rank": "전체 응시자 {0}명 중 {1}님은 전체에서 {2}등 (상위 {3}%)입니다.",
  "inAir.itvResultV2.label.entire_examinee": "전체 응시자",
  "inAir.itvResultV2.label.top_rank": "전체에서 O등",
  "inAir.itvResultV2.guide.msg12": "전체에서 O등 (상위 O%)입니다.",
  "inAir.itvResultV2.label.top_rank3": "직군 응시자는 총 O명이며,",
  "inAir.itvResultV2.label.job_examinee": "직군 응시자",
  "inAir.itvResultV2.guide.msg13":"전체 응시자 {0}명 중 {1}직군 응시자는 총 {2}명이며, {3}님은 {1}직군에서 {4}등(상위 {5}%)입니다.",
  "inAir.itvResultV2.label.job2": "OO직군",
  "inAir.itvResultV2.label.examinee_profile_compare": "전형 내 응시자 프로파일 비교",
  "inAir.itvResultV2.label.examinee": "응시자",
  "inAir.itvResultV2.label.entire_average": "전체평균",
  "inAir.itvResultV2.guide.msg14":"재직자 검사를 실시한 후 관리자 설정에서 대표/유사 구성원을 설정하시면 응시자와 재직자의 역량 수준을 비교하실 수 있습니다.",
  "inAir.itvResultV2.label.similarity": "대표구성원과의 유사도",
  "inAir.itvResultV2.guide.msg15": "대표 구성원으로 설정한 재직자가 없습니다.",
  "inAir.itvResultV2.label.summary": "종합",
  "inAir.itvResultV2.label.performance": "성과역량",
  "inAir.itvResultV2.label.growth": "성장역량",
  "inAir.itvResultV2.label.representative_member": "대표구성원",
  "inAir.itvResultV2.label.similar_member": "유사구성원",
  "inAir.itvResultV2.guide.msg16": "유사 구성원으로 설정한 재직자가 없습니다.",
  "inAir.itvResultV2.guide.msg17": "비슷한 유사 구성원 정보가 없습니다.",
  "inAir.itvResultV2.label.reliability": "신뢰 가능성",
  "inAir.itvResultV2.guide.msg18": "신뢰불가인 경우 아래 나타나는 키워드에 마우스를 올려 상세한 내용을 확인할 수 있습니다.",
  "inAir.itvResultV2.label.check_clip": "영상확인필요",
  "inAir.itvResultV2.label.cannot_trust": "신뢰불가",
  "inAir.itvResultV2.label.can_trust": "신뢰가능",
  "inAir.itvResultV2.guide.msg19": "응시 결과를 신뢰할 수 있습니다.",
  "inAir.itvResultV2.guide.msg20": "AI 게임 및 AI면접에서<br>안정적으로 응시하였으며,<br>이상 행동이 발견되지 않았습니다.",
  "inAir.itvResultV2.label.ai_game": "AI게임",
  "inAir.itvResultV2.label.ai_interview": "AI면접",
  "inAir.itvResultV2.label.job_fit": "직군 적합도",
  "inAir.itvResultV2.label.job_blind": "직군/직무 블라인드",
  "inAir.itvResultV2.label.summary_applicant": "응시자 특성 요약",
  "inAir.itvResultV2.guide.msg21": "각 키워드에 마우스를 올리면 해당하는 역량 명칭을 확인할 수 있습니다.",
  "inAir.itvResultV2.label.organization_unfit": "조직부적합",
  "inAir.itvResultV2.label.not_recommand": "비추천",
  "inAir.itvResultV2.label.apply_field": "지원 분야",
  "inAir.itvResultV2.label.screening_title": "전형명",
  "inAir.itvResultV2.label.estimation_score": "고성과예측점수",
  "inAir.itvResultV2.label.customizing_core_factor": "커스터마이징명 <br> 핵심요인",
  "inAir.itvResultV2.label.core_factor": "핵심요인",
  "inAir.itvResultV2.label.customizing_title": "커스터마이징명",
  "inAir.itvResultV2.label.estimation_score_blind": "고성과예측점수 블라인드",
  "inAir.itvResultV2.label.tscore": "T점수",
  "inAir.itvResultV2.label.percentage": "백분위점수",
  "inAir.itvResultV2.label.top_rank4": "직군 기준 {0}등/ {1}명(상위 {2}%)",
  "inAir.itvResultV2.label.top_rank5": "{0}등 / {1}명(상위 {2}%)",
  "inAir.itvResultV2.label.entire_average_score": "전체 평균 점수",
  "inAir.itvResultV2.label.entire_average_score_blind": "전체 평균 점수 블라인드",
  "inAir.itvResultV2.label.entire_examinee_base": "전체 응시자 기준 ",
  "result.v2Video.guide.msg1":"영상을 재생할수 없는 환경입니다.<br> Microsoft Edge, Google Chrome, Firefox 등 <br> 데스크탑PC에서 재생이 가능합니다.",
  "result.v2Video.label.basic_question": "기본 질문",
  "result.v2Video.label.situation_question": "상황 질문",
  "result.v2Video.label.struct_question": "심층/구조화 질문",
  "result.v2Video.label.customizing": "커스터마이징",
  "result.v2Video.label.msg2": "질문 내용이 없습니다.",
  "versionA.EXAM_STEP1AI_COMMON.label.selected_job": "개 직무 선택됨",
  "versionA.EXAM_STEP1AI_COMMON.label.no_selected_job": "선택된 직무 없음",
  "versionA.EXAM_STEP1AI_COMMON.label.visible_setting": "직무적합도 표시 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.close": "닫기",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg1": "직무적합도는 직군별로 최대 4개 까지 설정 가능합니다.",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg2": "직군/직무적합도 결과에 표시되는 직무를 선택하세요. (직군별 최대 4개까지 선택가능)",
  "versionA.EXAM_STEP1AI_COMMON.label.job_group": "직군",
  "versionA.EXAM_STEP1AI_COMMON.label.job": "직무",
  "versionA.EXAM_STEP1AI_COMMON.label.changed_capability": "개 역량명 변경됨",
  "versionA.EXAM_STEP1AI_COMMON.label.capability_setting": "역량명 변경 세부 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.confirm": "확인",
  "versionA.EXAM_STEP1AI_COMMON.label.reset": "초기화",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg3":"아래의 역량이름과 정의를 확인하시고 변경하고자 하는 역량 이름은 우측 공란에 작성하시기 바랍니다. (12 byte 이내)",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg4": "변경하고 싶지 않은 역량은 공란으로 두시면 됩니다.",
  "versionA.EXAM_STEP1AI_COMMON.label.change_capability": "변경 역량명",
  "versionA.EXAM_STEP1AI_COMMON.label.capability_name": "역량명",
  "versionA.EXAM_STEP1AI_COMMON.label.definition": "정의",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg5": "일괄적용 커스터 마이징을 선택하세요.",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg6": "직군별 선택을 적용하려면 직군 중 1개 이상을 선택해야 합니다.",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg7": "종료된 전형은 전형 종료일을 앞당길 수 없습니다.",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg8": "이 입력란을 작성하세요",
  "versionA.EXAM_STEP1AI_COMMON.error.msg1": "외부페이지 링크 주소는 반드시 http:// 혹은 https:// 로 시작해야 합니다.",
  "versionA.EXAM_STEP1AI_COMMON.alert.msg1": "설정을 저장하시겠습니까?",
  "versionA.EXAM_STEP1AI_COMMON.error.msg2": "callback이 없습니다.",
  "versionA.EXAM_STEP1AI_COMMON.error.msg3": "APP_NAME을 입력해 주세요. ex) /mrs2/manager , /admin 등등...",
  "versionA.EXAM_STEP1AI_COMMON.label.basic_setting": "기본설정",
  "versionA.EXAM_STEP1AI_COMMON.label.screening_name": "전형명",
  "versionA.EXAM_STEP1AI_COMMON.label.test_period": "응시기간",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg9":"※ 검사 종료 날짜 기준으로 14일 후에 포인트 정산이 이루어지며, 정산이 시작되면 응시기간 및 응시자 변경이 불가능합니다.",
  "versionA.EXAM_STEP1AI_COMMON.label.test_start_day": "응시시작일",
  "versionA.EXAM_STEP1AI_COMMON.label.test_start_time": "응시시작시간",
  "versionA.EXAM_STEP1AI_COMMON.label.test_end_day": "응시종료일",
  "versionA.EXAM_STEP1AI_COMMON.label.test_end_time": "응시종료시간",
  "versionA.EXAM_STEP1AI_COMMON.label.applicant_site": "응시자사이트",
  "versionA.EXAM_STEP1AI_COMMON.label.interviewer_setting": "AI 면접관 설정",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg10": "안녕하세요. 홍길동님. 반갑습니다. 지금부터 온라인 면접을 시작하겠습니다.",
  "versionA.EXAM_STEP1AI_COMMON.label.voice_prelisten": "목소리 미리듣기",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg11": "청취할 텍스트를 입력하여 사전에 목소리를 확인하세요.",
  "versionA.EXAM_STEP1AI_COMMON.label.voice_listen": "목소리듣기",
  "versionA.EXAM_STEP1AI_COMMON.label.voice_download": "[목소리 다운로드]",
  "versionA.EXAM_STEP1AI_COMMON.label.closing_setting": "맺음말 설정",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg12": "응시 완료 후 지원자에게 안내되는 맺음말을 설정해주세요.",
  "versionA.EXAM_STEP1AI_COMMON.label.default_closing": "기본 맺음말 적용",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg13": "※ 맺음말은 최대 3개까지 등록할 수 있습니다.",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg14": "맺음말을 입력해주세요 (최대 48자)",
  "versionA.EXAM_STEP1AI_COMMON.label.closing_setence": "맺음말",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg15": "이제 모든 온라인 면접이 종료되었습니다.",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg16": "긴 시간 할애해주셔서 감사드리며, 면접에 좋은 결과 있으시길 바랍니다.",
  "versionA.EXAM_STEP1AI_COMMON.label.external_link": "외부페이지 링크 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.external_link_use": "외부페이지 링크 설정 사용여부",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg17": "※ 응시 완료 후 외부 웹 페이지로 연결이 필요한 경우 설정해 주세요.",
  "versionA.EXAM_STEP1AI_COMMON.label.link_title": "링크 버튼 제목 입력",
  "versionA.EXAM_STEP1AI_COMMON.label.external_link_name": "외부페이지 링크 버튼이름",
  "versionA.EXAM_STEP1AI_COMMON.label.url": "URL 입력",
  "versionA.EXAM_STEP1AI_COMMON.label.external_link_url": "외부페이지 링크 주소",
  "versionA.EXAM_STEP1AI_COMMON.label.result_setting": "결과표 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.result_use": "결과표 순위 표시 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.result_allRank_use": "결과표에서 전체 순위/지망별 순위 표시",
  "versionA.EXAM_STEP1AI_COMMON.label.rank_use": "순위 표시여부",
  "versionA.EXAM_STEP1AI_COMMON.label.detail_use": "세부역량 특성 표시 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.capability_order": "역량순",
  "versionA.EXAM_STEP1AI_COMMON.label.high_order": "높은순",
  "versionA.EXAM_STEP1AI_COMMON.label.low_order": "낮은순",
  "versionA.EXAM_STEP1AI_COMMON.label.detail_capability": "세부역량 특성 표시 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.fit_use": "직무적합도 표시 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.selected_job_fit": "선택된 직무 적합도",
  "versionA.EXAM_STEP1AI_COMMON.label.recommand_use": "추천도 표시 설정",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg18": "지원자 별 결과표에 추천도 키워드 표시를 설정할 수 있습니다.",
  "versionA.EXAM_STEP1AI_COMMON.label.high_recommand": "매우 추천",
  "versionA.EXAM_STEP1AI_COMMON.label.recommand": "추천",
  "versionA.EXAM_STEP1AI_COMMON.label.normal": "보통",
  "versionA.EXAM_STEP1AI_COMMON.label.not_recommand": "비추천",
  "versionA.EXAM_STEP1AI_COMMON.label.capability_name_use": "역량명 변경 설정",
  "versionA.EXAM_STEP1AI_COMMON.label.setting": "설정",
  "versionA.EXAM_STEP1AI_COMMON.label.selected_question": "개 질문 설정됨",
  "versionA.EXAM_STEP1AI_COMMON.guide.msg19":"※ 변경된 역량명은 지원자 개별 결과표에만 적용됩니다. (엑셀 결과표에는 변경된 사항이 적용되지 않습니다)",
  "versionA.EXAM_STEP1AI_COMMON.label.agreement": "정보제공 동의서",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg1": "커스터마이징 질문설정이 완료되지 않았습니다",
  "versionA.EXAM_STEP4AI_COMMON.alert.msg1": "설정을 저장하시겠습니까?",
  "versionA.EXAM_STEP4AI_COMMON.label.basic_question": "기본질문",
  "versionA.EXAM_STEP4AI_COMMON.label.situation_reaction": "상황대처",
  "versionA.EXAM_STEP4AI_COMMON.label.struct_conversation": "심층대화",
  "versionA.EXAM_STEP4AI_COMMON.label.custom_question": "맞춤질문",
  "versionA.EXAM_STEP4AI_COMMON.label.minute": "분",
  "versionA.EXAM_STEP4AI_COMMON.label.maximum_requireTime": "최대 소요 시간",
  "versionA.EXAM_STEP4AI_COMMON.label.job_requireTime": "직군별 소요시간",
  "versionA.EXAM_STEP4AI_COMMON.label.close": "닫기",
  "versionA.EXAM_STEP4AI_COMMON.label.maximum": "최대",
  "versionA.EXAM_STEP4AI_COMMON.label.minute_require": "분 소요",
  "versionA.EXAM_STEP4AI_COMMON.label.require": "소요",
  "versionA.EXAM_STEP4AI_COMMON.label.division": "구분",
  "versionA.EXAM_STEP4AI_COMMON.label.neuroscience_game": "뇌 과학 게임",
  "versionA.EXAM_STEP4AI_COMMON.label.question_reponse": "질의 응답",
  "versionA.EXAM_STEP4AI_COMMON.label.sum": "합계",
  "versionA.EXAM_STEP4AI_COMMON.label.set_question": "개 질문 설정됨",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg2": "직군 설정을 완료하지 않았습니다.",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg3": "인자가 잘못되었습니다",
  "versionA.EXAM_STEP4AI_COMMON.label.question_number": "질문번호",
  "versionA.EXAM_STEP4AI_COMMON.label.question_content": "질문내용",
  "versionA.EXAM_STEP4AI_COMMON.label.thinking_time": "생각시간",
  "versionA.EXAM_STEP4AI_COMMON.label.response_time": "답변시간",
  "versionA.EXAM_STEP4AI_COMMON.label.second": "초",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg4": "모든 응시자에게 최대 5개의 질문을 등록할 수 있습니다.",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg5": "직군별 최대 5개의 질문을 등록할 수 있습니다.",
  "versionA.EXAM_STEP4AI_COMMON.label.question_content_setting": "질문내용설정",
  "versionA.EXAM_STEP4AI_COMMON.label.thinking_time_setting": "생각시간 설정 가능 범위",
  "versionA.EXAM_STEP4AI_COMMON.label.response_time_setting": "답변시간 설정 가능 범위",
  "versionA.EXAM_STEP4AI_COMMON.label.job_question_register": "직군별 질문 등록",
  "versionA.EXAM_STEP4AI_COMMON.label.all_question_register": "일괄 질문 등록",
  "versionA.EXAM_STEP4AI_COMMON.label.confirm": "확인",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg6":"이미 응시를 시작했거나 기존 질문에 답변을 완료한 응시자가 존재하여 설정 변경이 불가합니다.<br><br>해당 응시자를 \"결과초기화\" 하신 후 진행해주세요.",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg7": "질문 내용을 입력해 주세요.",
  "versionA.EXAM_STEP4AI_COMMON.label.reset": "초기화",
  "versionA.EXAM_STEP4AI_COMMON.alert.msg2": "초기화 하시겠습니까",
  "versionA.EXAM_STEP4AI_COMMON.alert.msg3": "callback이 없습니다.",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg8": "기본질문, 상황대처, 심층대화, 맞춤질문 질문 구성을 확인할 수 있습니다. ",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg9": "맞춤질문(커스터마이징) 질문 설정을 통해 원하는 질문을 추가할 수 있습니다.",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg10": "지난 전형에서 사용하셨던 질문 설정을 불러와서 사용할 수 있습니다.",
  "versionA.EXAM_STEP4AI_COMMON.label.question_list": "질문구성",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg11": "질문은 다음과 같은 순서대로 제시됩니다.",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg12": "자기소개, 장단점과 같은 기본적인 질문이 제시됩니다.",
  "versionA.EXAM_STEP4AI_COMMON.label.situation_reaction2": "상황대처(상황질문)",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg13": "다양한 상황을 가정하여 질문이 제시되고, 지원자는 실제 답변하는 것처럼 응답하게 됩니다. (2개 질문)",
  "versionA.EXAM_STEP4AI_COMMON.label.struct_conversation2": "심층대화(심층구조화 질문)",
  "versionA.EXAM_STEP4AI_COMMON.guide.msg14": "지원자의 반응 특성을 분석한 결과를 바탕으로 심층구조화 질문이 제시됩니다.",
  "versionA.EXAM_STEP4AI_COMMON.label.custom_question2": "맞춤질문(커스터마이징 질문)",
  "versionA.EXAM_STEP4AI_COMMON.label.custom_question3": "커스터마이징 질문",
  "versionA.EXAM_STEP4AI_COMMON.label.no_apply": "적용안함",
  "versionA.EXAM_STEP4AI_COMMON.label.all_apply": "일괄적용",
  "versionA.EXAM_STEP4AI_COMMON.label.job_apply": "직군별 선택적용",
  "versionA.EXAM_STEP4AI_COMMON.label.question_setting": "질문설정",
  "versionB.EXAM_STEP1AI_COMMON.label.selected_job": "선택된 직무 적합도",
  "versionB.EXAM_STEP1AI_COMMON.label.no_selected_job": "선택된 직무 없음",
  "versionB.EXAM_STEP1AI_COMMON.label.job_visible_setting": "직무적합도 표시 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.close": "닫기",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg1": "직무적합도는 직군별로 최대 4개 까지 설정 가능합니다.",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg2": "※ 직군/직무적합도 결과에 표시되는 직무를 선택하세요. (직군별 최대 4개까지 선택가능)",
  "versionB.EXAM_STEP1AI_COMMON.label.job_group": "직군",
  "versionB.EXAM_STEP1AI_COMMON.label.job": "직무",
  "versionB.EXAM_STEP1AI_COMMON.label.changed_capability": "O개 역량명 변경됨",
  "versionB.EXAM_STEP1AI_COMMON.label.capability_setting": "역량명 변경 세부 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.confirm": "확인",
  "versionB.EXAM_STEP1AI_COMMON.label.reset": "초기화",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg3":"아래의 역량이름과 정의를 확인하시고 변경하고자 하는 역량 이름은 우측 공란에 작성하시기 바랍니다. (12 byte 이내)",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg4": "변경하고 싶지 않은 역량은 공란으로 두시면 됩니다.",
  "versionB.EXAM_STEP1AI_COMMON.label.change_capability": "변경 역량명",
  "versionB.EXAM_STEP1AI_COMMON.label.cpability_name": "역량명",
  "versionB.EXAM_STEP1AI_COMMON.label.definition": "정의",
  "versionB.EXAM_STEP1AI_COMMON.label.customizing": "커스터마이징",
  "versionB.EXAM_STEP1AI_COMMON.label.no_apply": "적용안함",
  "versionB.EXAM_STEP1AI_COMMON.label.no_selected": "선택안함",
  "versionB.EXAM_STEP1AI_COMMON.label.custom_setting": "커스터마이징 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.all_apply": "일괄적용",
  "versionB.EXAM_STEP1AI_COMMON.label.job_apply": "직군별 선택적용",
  "versionB.EXAM_STEP1AI_COMMON.label.result_use": "결과표 표시 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.result_custom_use": "결과표에서 커스터마이징 설정 표시",
  "versionB.EXAM_STEP1AI_COMMON.label.custom_setting_use": "커스터마이징 설정 표시여부",
  "versionB.EXAM_STEP1AI_COMMON.label.custom_use": "커스터마이징 사용여부",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg5": "직군별 선택을 적용하려면 직군 중 1개 이상을 선택해야 합니다.",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg6": "종료된 전형은 전형 종료일을 앞당길 수 없습니다.",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg7": "이 입력란을 작성하세요",
  "versionB.EXAM_STEP1AI_COMMON.error.msg1": "외부페이지 링크 주소는 반드시 http:// 혹은 https:// 로 시작해야 합니다.",
  "versionB.EXAM_STEP1AI_COMMON.alert.msg1": "설정을 저장하시겠습니까?",
  "versionB.EXAM_STEP1AI_COMMON.error.msg2": "callback이 없습니다.",
  "versionB.EXAM_STEP1AI_COMMON.error.msg3": "callback이 함수가 아닌게 들어왔네요.",
  "versionB.EXAM_STEP1AI_COMMON.label.basic_setting": "기본설정",
  "versionB.EXAM_STEP1AI_COMMON.label.screening_name": "전형명",
  "versionB.EXAM_STEP1AI_COMMON.label.applicant_detail": "응시자 상세",
  "versionB.EXAM_STEP1AI_COMMON.label.newcomer": "신입",
  "versionB.EXAM_STEP1AI_COMMON.label.career": "경력",
  "versionB.EXAM_STEP1AI_COMMON.label.test_period": "응시기간",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg8":"검사 종료 날짜 기준으로 14일 후에 포인트 정산이 이루어지며, 정산이 시작되면 응시기간 및 응시자 변경이 불가능합니다.",
  "versionB.EXAM_STEP1AI_COMMON.label.test_start_day": "응시시작일",
  "versionB.EXAM_STEP1AI_COMMON.label.test_start_time": "응시시작시간",
  "versionB.EXAM_STEP1AI_COMMON.label.test_end_day": "응시종료일",
  "versionB.EXAM_STEP1AI_COMMON.label.test_end_time": "응시종료시간",
  "versionB.EXAM_STEP1AI_COMMON.label.applicant_site": "응시자사이트",
  "versionB.EXAM_STEP1AI_COMMON.label.interviewer_setting": "AI 면접관 설정",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg9": "안녕하세요. 홍길동님. 반갑습니다. 지금부터 온라인 면접을 시작하겠습니다.",
  "versionB.EXAM_STEP1AI_COMMON.label.voice_prelisten": "목소리 미리듣기",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg10": "청취할 텍스트를 입력하여 사전에 목소리를 확인하세요",
  "versionB.EXAM_STEP1AI_COMMON.label.voice_listen": "목소리듣기",
  "versionB.EXAM_STEP1AI_COMMON.label.voice_download": "[목소리 다운로드]",
  "versionB.EXAM_STEP1AI_COMMON.label.closing_setting": "맺음말 설정",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg11": "응시 완료 후 지원자에게 안내되는 맺음말을 설정해주세요.",
  "versionB.EXAM_STEP1AI_COMMON.label.default_closing": "기본 맺음말 적용",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg12": "※ 맺음말은 최대 3개까지 등록할 수 있습니다.",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg13": "맺음말을 입력해주세요 (최대 48자)",
  "versionB.EXAM_STEP1AI_COMMON.label.closing_setence": "맺음말",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg14": "이제 모든 온라인 면접이 종료되었습니다.",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg15": "긴 시간 할애해주셔서 감사드리며, 면접에 좋은 결과 있으시길 바랍니다.",
  "versionB.EXAM_STEP1AI_COMMON.label.external_link": "외부페이지 링크 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.external_link_use": "외부페이지 링크 설정 사용여부",
  "versionB.EXAM_STEP1AI_COMMON.guide.msg16": "※ 응시 완료 후 외부 웹 페이지로 연결이 필요한 경우 설정해 주세요.",
  "versionB.EXAM_STEP1AI_COMMON.label.link_title": "링크 버튼 제목 입력",
  "versionB.EXAM_STEP1AI_COMMON.label.external_link_name": "외부페이지 링크 버튼이름",
  "versionB.EXAM_STEP1AI_COMMON.label.url": "URL 입력",
  "versionB.EXAM_STEP1AI_COMMON.label.external_link_url": "외부페이지 링크 주소",
  "versionB.EXAM_STEP1AI_COMMON.label.result_setting": "결과표 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.detail_use": "세부역량 특성 표시 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.capability_order": "역량순",
  "versionB.EXAM_STEP1AI_COMMON.label.high_order": "높은순",
  "versionB.EXAM_STEP1AI_COMMON.label.low_order": "낮은순",
  "versionB.EXAM_STEP1AI_COMMON.label.detail_capability": "세부역량 특성 표시 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.fit_use": "직무적합도 표시 설정",
  "versionB.EXAM_STEP1AI_COMMON.label.agreement": "정보제공 동의서",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg1": "커스터마이징 질문설정이 완료되지 않았습니다",
  "versionB.EXAM_STEP4AI_COMMON.alert.msg1": "설정을 저장하시겠습니까?",
  "versionB.EXAM_STEP4AI_COMMON.label.basic_question": "기본질문",
  "versionB.EXAM_STEP4AI_COMMON.label.situation_reaction": "상황대처",
  "versionB.EXAM_STEP4AI_COMMON.label.struct_conversation": "심층대화",
  "versionB.EXAM_STEP4AI_COMMON.label.custom_question": "맞춤질문 등록",
  "versionB.EXAM_STEP4AI_COMMON.label.minute": "분",
  "versionB.EXAM_STEP4AI_COMMON.label.maximum_requireTime": "최대 소요시간",
  "versionB.EXAM_STEP4AI_COMMON.label.job_requireTime": "직군별 소요시간",
  "versionB.EXAM_STEP4AI_COMMON.label.close": "닫기",
  "versionB.EXAM_STEP4AI_COMMON.label.maximum": "최대",
  "versionB.EXAM_STEP4AI_COMMON.label.require_time": "소요 시간",
  "versionB.EXAM_STEP4AI_COMMON.label.require": "소요",
  "versionB.EXAM_STEP4AI_COMMON.label.division": "구분",
  "versionB.EXAM_STEP4AI_COMMON.label.neuroscience_game": "뇌 과학 게임",
  "versionB.EXAM_STEP4AI_COMMON.label.question_reponse": "질의 응답",
  "versionB.EXAM_STEP4AI_COMMON.label.sum": "합계",
  "versionB.EXAM_STEP4AI_COMMON.label.set_question": "개 질문 설정됨",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg2": "직군 설정을 완료하지 않았습니다.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg3": "인자가 잘못되었습니다",
  "versionB.EXAM_STEP4AI_COMMON.label.question_number": "질문번호",
  "versionB.EXAM_STEP4AI_COMMON.label.question_content": "질문내용",
  "versionB.EXAM_STEP4AI_COMMON.label.thinking_time": "생각시간",
  "versionB.EXAM_STEP4AI_COMMON.label.response_time": "답변시간",
  "versionB.EXAM_STEP4AI_COMMON.label.second": "초",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg4": "모든 응시자에게 최대 10개의 질문을 등록할 수 있습니다.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg5": "직군별 최대 10개의 질문을 등록할 수 있습니다.",
  "versionB.EXAM_STEP4AI_COMMON.label.question_content_setting": "질문내용설정",
  "versionB.EXAM_STEP4AI_COMMON.label.question_time_settinge": "질문시간설정",
  "versionB.EXAM_STEP4AI_COMMON.label.thinking_time_setting": "생각시간 설정 가능 범위 : ",
  "versionB.EXAM_STEP4AI_COMMON.label.response_time_setting": "답변시간 설정 가능 범위 : ",
  "versionB.EXAM_STEP4AI_COMMON.label.job_question_register": "직군별 질문 등록",
  "versionB.EXAM_STEP4AI_COMMON.label.all_question_register": "일괄 질문 등록",
  "versionB.EXAM_STEP4AI_COMMON.label.confirm": "확인",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg6":"이미 응시를 시작했거나 기존 질문에 답변을 완료한 응시자가 존재하여 설정 변경이 불가합니다.<br>해당 응시자를 \"결과초기화\" 하신 후 진행해주세요.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg7": "질문 내용을 입력해 주세요.",
  "versionB.EXAM_STEP4AI_COMMON.label.reset": "초기화",
  "versionB.EXAM_STEP4AI_COMMON.alert.msg2": "초기화 하시겠습니까",
  "versionB.EXAM_STEP4AI_COMMON.alert.msg3": "callback이 없습니다.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg8": "기본질문, 상황대처, 심층대화, 맞춤질문 질문 구성을 확인할 수 있습니다. ",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg9": "맞춤질문(커스터마이징) 질문 설정을 통해 원하는 질문을 추가할 수 있습니다.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg10": "지난 전형에서 사용하셨던 질문 설정을 불러와서 사용할 수 있습니다.",
  "versionB.EXAM_STEP4AI_COMMON.label.question_list": "질문구성",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg11": "질문은 다음과 같은 순서대로 제시됩니다.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg12": "자기소개, 장단점과 같은 기본적인 질문이 제시됩니다.",
  "versionB.EXAM_STEP4AI_COMMON.label.situation_reaction2": "상황대처(상황질문)",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg13": "다양한 상황을 가정하여 질문이 제시되고, 지원자는 실제 답변하는 것처럼 응답하게 됩니다. (2개 질문)",
  "versionB.EXAM_STEP4AI_COMMON.label.struct_conversation2": "심층대화(심층구조화 질문)",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg14": "지원자의 반응 특성을 분석한 결과를 바탕으로 심층구조화 질문이 제시됩니다.",
  "versionB.EXAM_STEP4AI_COMMON.label.custom_question2": "맞춤질문(커스터마이징 질문)",
  "versionB.EXAM_STEP4AI_COMMON.label.custom_question3": "커스터마이징 질문",
  "versionB.EXAM_STEP4AI_COMMON.label.no_apply": "적용안함",
  "versionB.EXAM_STEP4AI_COMMON.label.all_apply": "일괄적용",
  "versionB.EXAM_STEP4AI_COMMON.label.job_apply": "직군별 선택적용",
  "versionB.EXAM_STEP4AI_COMMON.label.question_setting": "질문설정",
  "versionB.EXAM_STEP4AI_COMMON.label.korean": "한국어(기본)",
  "versionB.EXAM_STEP4AI_COMMON.label.english": "영어(미국)",
  "versionB.EXAM_STEP4AI_COMMON.label.chinese": "중국어",
  "versionB.EXAM_STEP4AI_COMMON.label.japanes": "일본어",
  "versionB.EXAM_STEP4AI_COMMON.label.select": "선택",
  "versionB.EXAM_STEP4AI_COMMON.label.each": "개",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg15":"\"순서 섞기\" 기능을 활용하시면 응시자들에 임의로 질문이 주어집니다.<br>Ex. 10개의 질문을 등록 후 사용 질문 개수를 3개로 설정하면 10개 중 3개 질문이 무작위로 제시됩니다.<br>외국어로 질문하고 싶다면 \"출력 언어 설정\" 기능을 활용하십시오. 폰트가 깨지는 현상을 방지할 수 있습니다.",
  "versionB.EXAM_STEP4AI_COMMON.label.order_mix": "순서 섞기",
  "versionB.EXAM_STEP4AI_COMMON.label.question_count": "사용 질문 개수",
  "versionB.EXAM_STEP4AI_COMMON.label.language_setting": "언어 설정",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg16":"이미 응시를 시작했거나 기존 질문에 답변을 완료한 응시자가 존재하여 설정 변경이 불가합니다.<br>해당 응시자를 \"결과초기화\" 하신 후 진행해주세요.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg17": "질문을 설정해주세요.",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg18": "질문내용을 입력해주세요",
  "versionB.EXAM_STEP4AI_COMMON.guide.msg19": "사용 질문 개수를 선택하거나, 순서 섞기를 OFF로 설정해주세요.",
  "versionB.EXAM_STEP4AI_COMMON.label.read_more": "자세히보기",
  "versionB.EXAM_STEP5AI_COMMON.label.selected_job": "개 직무 선택됨",
  "versionB.EXAM_STEP5AI_COMMON.label.no_selected_job": "선택된 직무 없음.",
  "versionB.EXAM_STEP5AI_COMMON.label.visible_setting": "직무적합도 표시 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.close": "닫기",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg1": "직무적합도는 직군별로 최대 4개 까지 설정 가능합니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg2": "※ 직군/직무적합도 결과에 표시되는 직무를 선택하세요. (직군별 최대 4개까지 선택가능)",
  "versionB.EXAM_STEP5AI_COMMON.label.job_group": "직군",
  "versionB.EXAM_STEP5AI_COMMON.label.job": "직무",
  "versionB.EXAM_STEP5AI_COMMON.label.changed_job": "개 직군/직무명칭 변경됨",
  "versionB.EXAM_STEP5AI_COMMON.label.job_name_setting_detail": "직군/직무명칭 변경 세부 설정",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg3": "아래의 직군/직무명을 확인하시고 변경하고자 하는 역량 이름은 우측 공란에 작성하시기 바랍니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg4": "변경하고 싶지 않은 직군/직무명은 공란으로 두시면 됩니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg5": "직군/직무별로 입력할 수 있는 글자수가 다릅니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.changed_job_name": "변경 직군/직무명",
  "versionB.EXAM_STEP5AI_COMMON.label.job_and_job_group": "직군/직무명",
  "versionB.EXAM_STEP5AI_COMMON.label.changed_capability": "개 역량명 변경됨",
  "versionB.EXAM_STEP5AI_COMMON.label.capability_setting": "역량명 변경 세부 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.confirm": "확인",
  "versionB.EXAM_STEP5AI_COMMON.label.reset": "초기화",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg6": "구성원이 없습니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg7": "※ 응시자 구분이 [대표/유사 구성원 대상자]로 설정된 재직자 AI 면접 결과가 있어야 설정 가능합니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg8":"[대표/유사 구성원 대상자]로 설정된 재직자 검사가 없을 경우, [사용안함]으로 체크 후 다음으로 진행하시기 바랍니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.change_capability": "변경 역량명",
  "versionB.EXAM_STEP5AI_COMMON.label.cpability_name": "역량명",
  "versionB.EXAM_STEP5AI_COMMON.label.definition": "정의",
  "versionB.EXAM_STEP5AI_COMMON.label.search_input": "검색어 입력",
  "versionB.EXAM_STEP5AI_COMMON.label.all": "전체",
  "versionB.EXAM_STEP5AI_COMMON.label.representative_member_setting": "대표구성원 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.similar_member_setting": "유사구성원 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.no_use": "사용안함",
  "versionB.EXAM_STEP5AI_COMMON.label.all_set": "일괄설정",
  "versionB.EXAM_STEP5AI_COMMON.label.select": "선택",
  "versionB.EXAM_STEP5AI_COMMON.label.total": "총",
  "versionB.EXAM_STEP5AI_COMMON.label.person": "명",
  "versionB.EXAM_STEP5AI_COMMON.label.job_setting": "직군별설정",
  "versionB.EXAM_STEP5AI_COMMON.label.ai_interview": "온라인 AI 면접",
  "versionB.EXAM_STEP5AI_COMMON.label.picture_show": "사진 보기",
  "versionB.EXAM_STEP5AI_COMMON.label.picture_setting": "사진 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.save": "저장",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg1": "업로드할 사진을 선택하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg2": "jpg 파일을 업로드하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg3": "사진을 등록하시겠습니까?",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg4": "파일을 성공적으로 업로드 하였습니다.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg5": "사진 설정을 완료하였습니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.picture_show2": "사진보기",
  "versionB.EXAM_STEP5AI_COMMON.error.msg1": "파일 업로드를 실패하였습니다. 잘못된 형식의 데이터를 수정하여 다시 시도해주시기 바랍니다.",
  "versionB.EXAM_STEP5AI_COMMON.error.msg2": "파일 업로드를 실패하였습니다. 다시 시도해주시기 바랍니다.",
  "versionB.EXAM_STEP5AI_COMMON.error.msg3": "권장사이즈(3MB)에 맞는 파일을 업로드하세요.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg9":"최대 3MB의 jpg 파일을 업로드 할 수 있습니다.<br/>권장사이즈는 300x360입니다.(2.5 x 3 증명사진)",
  "versionB.EXAM_STEP5AI_COMMON.label.hidden": "개 숨김 설정됨",
  "versionB.EXAM_STEP5AI_COMMON.label.result_preview": "결과표 미리보기",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg10": "결과표에서 숨김처리 하고자 하는 항목을 OFF처리 시, 해당 항목을 제외하고 결과표가 출력됩니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.applicant": "지원자",
  "versionB.EXAM_STEP5AI_COMMON.label.member": "재직자",
  "versionB.EXAM_STEP5AI_COMMON.label.apply": "지원",
  "versionB.EXAM_STEP5AI_COMMON.label.work": "재직",
  "versionB.EXAM_STEP5AI_COMMON.label.field": "분야",
  "versionB.EXAM_STEP5AI_COMMON.label.department": "부서",
  "versionB.EXAM_STEP5AI_COMMON.label.result_use": "결과표 표시 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.setting": "설정",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg11": "※ 변경된 설정은 결과표 인쇄할 때도 동일하게 적용됩니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.score_kind": "점수 종류",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg12":"※ T점수와 백분위는 서로 호환 가능하지만, 표현되는 점수의 의미와 범위가 다르므로 해당 부분을 고려하여 설정하시기 바랍니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.tscore": "T점수",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg13": "지원자의 원 점수를 평균이 50점, 표준편차가 10점인 분포로 변환한 점수입니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg14": "T점수는 지원자들 간의 상대적인 수준을 비교하기 쉽도록 표준화한 것입니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg15":"평균이 50점이므로 점수가 50점보다 높을 때는 평균 이상, 50점보다 낮을 때는 평균 이하로 평가 할 수 있습니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg16": "T점수는 최소 20점 최대 80점의 범위를 지닙니다.",
  "versionB.EXAM_STEP5AI_COMMON.label.percentile_score": "백분위 점수",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg17": "지원자의 수준이 규준 집단 내에서 차지하는 상대적 위치를 백분율로 변환한 점수입니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg18":"99점은 이 점수보다 낮은 규준 집단 지원자가 99%라는 것으로, 지원자의 역량 수준이 규준 내 상위 1%임을 의미합니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg19":"반대로 1점은 이 점수보다 낮은 규준 집단 지원자가 1%라는 것으로 규준 내 상위 하위 1%임을 의미합니다.",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg20": "백분위는 최소 1점 최대 99점의 범위를 지닙니다.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg6": "대표구성원을 설정하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg7": "대표구성원 일괄설정을 선택하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg8": "대표구성원 직군별설정을 선택하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg9": "유사구성원을 설정하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg10": "유사구성원 일괄설정을 선택하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg11": "유사구성원 직군별설정을 선택하세요.",
  "versionB.EXAM_STEP5AI_COMMON.alert.msg12": "설정을 저장하시겠습니까?",
  "versionB.EXAM_STEP5AI_COMMON.error.msg4": "callback이 없습니다.",
  "versionB.EXAM_STEP5AI_COMMON.error.msg5": "APP_NAME을 입력해 주세요. ex) /mrs2/manager , /admin 등등...",
  "versionB.EXAM_STEP5AI_COMMON.label.result_setting": "결과표 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.score_setting": "점수 표시 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.percentile_score2": "백분위점수",
  "versionB.EXAM_STEP5AI_COMMON.label.description": "설명보기",
  "versionB.EXAM_STEP5AI_COMMON.label.job_visible_setting": "직무적합도 표시 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.selected_job_fit": "선택된 직무 적합도",
  "versionB.EXAM_STEP5AI_COMMON.label.capability_name_use": "역량명 변경 설정",
  "versionB.EXAM_STEP5AI_COMMON.label.capability_name_setting": "역량명칭변경",
  "versionB.EXAM_STEP5AI_COMMON.label.job_name_setting": "직군/직무명칭변경",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg21":"※ 변경된 역량명은 지원자 개별 결과표에만 적용됩니다. (엑셀 결과표에는 변경된 사항이 적용되지 않습니다)",
  "versionB.EXAM_STEP5AI_COMMON.label.selected_question": "개 질문 설정됨",
  "versionB.EXAM_STEP5AI_COMMON.label.representative_similar_member_setting": "대표/유사 구성원 설정",
  "versionB.EXAM_STEP5AI_COMMON.guide.msg22":"※ 변경된 직군/직무명은 지원자 개별 결과표에만 적용됩니다. (엑셀 결과표에는 변경된 사항이 적용되지 않습니다.)",
  "inAir.Isac.job_group.sales": "영업/판매",
  "inAir.Isac.job_group.development": "연구/개발",
  "inAir.Isac.job_group.service": "서비스",
  "inAir.Isac.job_group.engineer": "엔지니어",
  "inAir.Isac.job_group.management": "사무/관리",
  "inAir.Isac.job_group.production": "생산",
  "inAir.Isac.job_group.production_fit": "생산(fit+)",
  "inAir.Isac.exam_method.online": "온라인",
  "inAir.Isac.exam_method.offline": "오프라인",
  "inAir.Isac.exam_status.ready": "진행전",
  "inAir.Isac.exam_status.active": "진행중",
  "inAir.Isac.exam_status.completed": "마감",
  "inAir.Isac.custom_kind.all_apply": "일괄적용",
  "inAir.Isac.custom_kind.job_apply": "직군별 적용",
  "inAir.Isac.custom_kind.none_apply": "적용 안함",
  "inAir.Isac.custom_set_status.recruit_answer_not_completed": "채용절차 설문 미완료",
  "inAir.Isac.custom_set_status.talent_answer_not_completed": "인재유형 설문 미완료",
  "inAir.Isac.custom_set_status.detail_not_completed": "세부설정 미완료",
  "inAir.Isac.custom_set_status.completed": "완료",
  "inAir.Isac.interview_custom_set_status.basic_survey_undone": "기본정보 설문 미완료",
  "inAir.Isac.interview_custom_set_status.talent_suvey_undone": "중요 인재상 설문 미완료",
  "inAir.Isac.interview_custom_set_status.member_survey_undone": "재직자 설정 미완료",
  "inAir.Isac.interview_custom_set_status.done": "완료",
  "inAir.Isac.male_yn.yes": "남",
  "inAir.Isac.male_yn.no": "여",
  "inAir.Isac.analysis_status.analyzing": "분석중",
  "inAir.Isac.analysis_status.part_done": "부분완료",
  "inAir.Isac.analysis_status.done": "분석완료",
  "inAir.Isac.analysis_status.fail": "분석실패",
  "inAir.Isac.mail_result.success": "성공",
  "inAir.Isac.mail_result.mailing": "발송중",
  "inAir.Isac.mail_result.fail": "실패",
  "inAir.Isac.mail_result.open": "열람",
  "inAir.Isac.grade.very_good": "매우우수",
  "inAir.Isac.grade.good": "우수",
  "inAir.Isac.grade.normal": "보통",
  "inAir.Isac.grade.little_bad": "다소미흡",
  "inAir.Isac.grade.bad": "미흡",
  "inAir.Isac.grade.very_bad": "매우미흡",
  "inAir.Isac.exam_step.login": "온라인 AI 면접 접속",
  "inAir.Isac.exam_step.re_login": "온라인 AI 면접 재접속",
  "inAir.Isac.exam_step.connection_count_reset": "관리자 - 접속횟수초기화",
  "inAir.Isac.exam_step.answer_and_result_reset": "관리자 - 결과초기화",
  "inAir.Isac.exam_step.take_exam_completed": "응시완료",
  "inAir.Isac.exam_step.calibration": "웹캠/마이크 체크",
  "inAir.Isac.exam_step.regist_face": "안면등록",
  "inAir.Isac.exam_step.warm_up_question": "몸풀기 질문",
  "inAir.Isac.exam_step.v3self": "자기소개",
  "inAir.Isac.exam_step.v3qna_common": "기본질문",
  "inAir.Isac.exam_step.bv_likert": "성향파악",
  "inAir.Isac.exam_step.v3qna_situation": "상황대처",
  "inAir.Isac.exam_step.v3qna_struct": "심층대화",
  "inAir.Isac.exam_step.v3qna_custom": "맞춤질문",
  "inAir.Isac.exam_step.selecting_game": "선택중",
  "inAir.Isac.exam_step.tolt": "공 탑 쌓기",
  "inAir.Isac.exam_step.stroop2": "색 단어 일치 판단",
  "inAir.Isac.exam_step.nback": "도형 위치 기억하기",
  "inAir.Isac.exam_step.fwt2": "공 무게 맞추기",
  "inAir.Isac.exam_step.ert_p1_p2": "감정 변화 맞추기",
  "inAir.Isac.exam_step.ert_p2_p2": "감정 맞추기",
  "inAir.Isac.exam_step.pct": "날씨 맞추기",
  "inAir.Isac.exam_step.cct": "카드 뒤집기",
  "inAir.Isac.exam_step.sst": "글자-숫자 분류하기",
  "inAir.Isac.exam_step.dat": "방향 바꾸기",
  "inAir.Isac.exam_step.eefrt2": "상금 모으기",
  "inAir.Isac.exam_step.bart2": "풍선불기",
  "inAir.Isac.exam_step.length": "입 길이 맞추기",
  "inAir.Isac.exam_step.ug": "수익 분배하기",
  "inAir.Isac.exam_step.spc1": "같은 그림 만들기",
  "inAir.Isac.exam_step.spc2": "같은 그림 맞추기",
  "inAir.Isac.exam_step.mrt": "블록 쌓기",
  "inAir.Isac.exam_step.ddt": "보상선호",
  "inAir.Isac.exam_step.fis2": "도형선호",
  "inAir.Isac.exam_step.ppt2": "취향추론",
  "inAir.Isac.reliability_code.response_reliability_impossibility": "신뢰불가",
  "inAir.Isac.reliability_code.response_reliability_possibility": "신뢰가능",
  "inAir.Isac.reliability_code.video_confirm_needed": "영상확인필요",
  "inAir.Isac.exam_step_state.complete": "완료",
  "inAir.Isac.exam_step_state.start": "시작",
  "inAir.Isac.exam_step_state.fail": "실패",
  "inAir.Isac.error.msg1": "해당 코드값이 없습니다",
  "inAir.Isac.error.msg2": "getList는 key, attr 두개가 필요합니다",
  "inAir.Isac.error.msg3": "getList는 key, attrKey,attrValue 세개가 필요합니다",
  "inAir.Isac.error.msg4": "array 나 object 혹은 string만 허용합니다!",
  "inAir.Isac.ProcessTab.exam_setting": "검사 설정",
  "inAir.Isac.ProcessTab.applicant_setting": "응시자 설정",
  "inAir.Isac.ProcessTab.mail_sms_setting": "안내메일&amp;SMS 설정/발송",
  "inAir.Isac.ProcessTab.basic_setting": "기본설정",
  "inAir.Isac.ProcessTab.recruit_setting": "채용절차 설문",
  "inAir.Isac.ProcessTab.talent_setting": "인재유형 설문",
  "inAir.Isac.ProcessTab.detail_setting": "세부설정",
  "inAir.Isac.getPoint.error.msg1": "해당 type이 존재하지 않습니다.",
  "inAir.Isac.getPoint.label.guidance": "제품별 구매 Point 안내",
  "inAir.Isac.getPoint.label.infinite": "무제한",
  "inAir.Isac.getPoint.label.own_point": "보유 포인트",
  "inAir.Isac.getPoint.label.use_available": "사용가능",
  "inAir.Isac.getPoint.label.use_complete": "사용완료",
  "inAir.Isac.getPoint.label.total": "전체",
  "inAir.Isac.getPoint.label.mid": "중",
  "inAir.Isac.getPoint.label.each": "건",
  "inAir.Isac.getPoint.label.sms_remain": "SMS 잔여 건수",
  "inAir.Isac.getPoint.error.msg2": "잘못된 type입니다",
  "inAir.Isac.getPoint.label.register_available_people": "※ 온라인 AI면접 등록가능 인원",
  "inAir.Isac.getPoint.label.person": "명",
  "inAir.Isac.error.msg5": "정보를 불러오는데 실패했습니다. 다시 시도해주시기 바랍니다.",
  "inAir.Isac.error.msg6": "등록된 번호가 없습니다",
  "inAir.Isac.error.msg7": "spf에 등록된 이메일이 아닙니다.",
  "inAir.Isac.error.msg8":"SPF 등록이 확인되지 않은 메일주소입니다. SPF등록이 되지 않은 경우 입력해주신 메일 주소가 아닌 {0}로 보내는 주소가 자동 변환되어 발송됩니다.",
  "inAir.Isac.error.msg9":" SPF등록이 되지 않은 경우 입력해주신 메일 주소가 아닌 OOOO주소로 보내는 주소가 자동 변환되어 발송됩니다.",
  "inAir.Isac.getPoint.guide.msg1": "응시자 등록 시 포인트가 차감됩니다.",
  "inAir.Isac.getPoint.guide.msg2": "미응시인 응시자는 설정한 응시기간 종료 2주 후 자동으로 포인트가 환불됩니다.",
  "inAir.Isac.getPoint.guide.msg3": "미완료, 완료 상태의 응시자는 응시자 정보나 결과를 삭제해도 포인트 환불이 불가능합니다.",
  "inAir.Isac.getPoint.label.remain": "잔여량 안내",
  "inAir.layerPopEMail.guide.msg1": "검사 실시 안내 드립니다.",
  "inAir.layerPopEMail.guide.msg2":"안녕하세요. $성명$님, $회사명$입니다. 검사가 다음과 같이 진행되오니, 기간 내에 반드시 응시 완료하여 주시기 바랍니다.",
  "inAir.layerPopEMail.label.title": "[검사 일정 안내]",
  "inAir.layerPopEMail.label.content": "내용",
  "inAir.layerPopEMail.label.exam_period": "응시기간",
  "inAir.layerPopEMail.guide.msg3": "※ 반드시 기한 내에 응시 완료하여 주시기 바랍니다.",
  "inAir.layerPopEMail.label.required_time": "소요시간",
  "inAir.layerPopEMail.label.required_time2": "약 $소요시간$분",
  "inAir.layerPopEMail.label.examinee_site": "응시사이트",
  "inAir.layerPopEMail.label.examinee_site2": "$응시사이트$",
  "inAir.layerPopEMail.label.login_info": "로그인정보",
  "inAir.layerPopEMail.label.name": "이름: ",
  "inAir.layerPopEMail.label.name2": "이름: $성명$",
  "inAir.layerPopEMail.label.certificate_code": "인증코드",
  "inAir.layerPopEMail.label.certificate_code2": "인증코드: $인증코드$",
  "inAir.layerPopEMail.label.notification": "유의사항",
  "inAir.layerPopEMail.guide.msg4": "1. 검사 시작 전, 안내문을 반드시 꼼꼼히 숙지하여 주시기 바랍니다.",
  "inAir.layerPopEMail.guide.msg5":"2. 각 유형 혹은 페이지별로 시간이 할당되어 있습니다. 시간 안배에 신경 쓰면서 진행해 주시기 바랍니다.",
  "inAir.layerPopEMail.guide.msg6":"3. 최신버전의 인터넷 익스플로러(Internet Explorer 11) 또는 웹브라우저 크롬(Chrome)에서 검사를 응시해 주시기 바랍니다.",
  "inAir.layerPopEMail.guide.msg7":"4. 검사 응시 시작 후에는 중단 없이 한 번에 응시 완료하셔야 합니다. 온전히 검사에 집중할 수 있는 환경을 미리 준비하시기 바랍니다.",
  "inAir.layerPopEMail.guide.msg8":"5. 유선인터넷 환경에서 검사를 응시해 주시기 바라며, 사전에 네트워크 연결 상태를 확인하시기 바랍니다. 검사 도중 네트워크 연결이 끊길 경우 검사가 중지될 수 있으며, 이에 대한 불이익은 책임지지 않습니다.",
  "inAir.layerPopEMail.guide.msg9": "6. 모바일 환경에서는 검사를 응시할 수 없습니다.",
  "inAir.layerPopEMail.guide.msg10": "7. 문제 유출 시 법적 책임을 물을 수 있습니다.",
  "inAir.layerPopEMail.guide.msg11": "온라인 면접 응시 안내 드립니다.",
  "inAir.layerPopEMail.label.name3": "$성명$",
  "inAir.layerPopEMail.label.company": "$회사명$",
  "inAir.layerPopEMail.guide.msg12":"안녕하세요. $성명$님, $회사명$입니다. 온라인 면접 다음과 같이 진행됩니다.<br>아래 내용을 반드시 숙지하시고, 온라인 면접 응시에 착오 없으시길 바랍니다.",
  "inAir.layerPopEMail.label.division": "구분",
  "inAir.layerPopEMail.label.exam_period2": "$응시기간$",
  "inAir.layerPopEMail.guide.msg13": "약 60분<br>※ 개인별 수행 시간에 따라 10분 정도 차이가 날 수 있습니다.",
  "inAir.layerPopEMail.label.guidance": "안내사항",
  "inAir.layerPopEMail.label.check_material": "[준비물]",
  "inAir.layerPopEMail.guide.msg14": "1. PC카메라/ 마이크 (노트북 카메라, 내장 마이크 사용가능) / 이어폰",
  "inAir.layerPopEMail.guide.msg15": "2. 마우스와 키보드",
  "inAir.layerPopEMail.guide.msg16": "3. 질문에 대한 답변 준비 (예 : 자기소개/장점 및 단점 소개)<br/>",
  "inAir.layerPopEMail.guide.msg17":"※ 이어폰을 사용하여 온라인 면접을 진행하시기 바랍니다. 외부로 출력되는 스피커를 사용할 경우 하울링(소리증폭현상)이 발생할 수 있습니다.",
  "inAir.layerPopEMail.guide.msg18": "※ 시스템 체크는 응시 기간 이전에 사전 확인이 가능합니다.",
  "inAir.layerPopEMail.guide.msg19": "응시자사이트에 접속하여 카메라/마이크를 사전에 체크하시기 바랍니다.",
  "inAir.layerPopEMail.label.interview_guidance": "[응시안내]",
  "inAir.layerPopEMail.guide.msg20": "1. 온라인 면접은 질의 응답과 게임 수행으로 구성되어 있습니다.",
  "inAir.layerPopEMail.guide.msg21": "2. 질의 응답의 경우 안내되는 질문에 충분히 생각을 하신 다음에 답변을 하시면 됩니다.",
  "inAir.layerPopEMail.guide.msg22":"3. 게임 수행의 경우 안내 되는 가이드의 내용을 잘 숙지하여 마우스 또는 키보드를 이용하여 게임을 수행하시면 됩니다.",
  "inAir.layerPopEMail.label.notification2": "[유의사항]",
  "inAir.layerPopEMail.guide.msg23": "1. 인터넷 브라우저 크롬(Google Chrome)에서만 응시가 가능합니다.",
  "inAir.layerPopEMail.guide.msg24":"2. 응시 시작 후에는 중단 없이 한 번에 응시 완료하셔야 합니다. 온전히 응시에 집중할 수 있는 환경을 미리 준비하시기 바랍니다.",
  "inAir.layerPopEMail.guide.msg25":"3. 유선인터넷 환경에서 응시해 주시기 바라며, 사전에 네트워크 연결 상태를 확인하시기 바랍니다. 응시 도중 네트워크 연결이 끊길 경우 응시가 중지될 수 있으며, 이에 대한 불이익은 책임지지 않습니다.",
  "inAir.layerPopEMail.guide.msg26": "4. 반드시 사용중인 모든 프로그램을 종료하고 온라인 면접을 진행하시기 바랍니다.",
  "inAir.layerPopEMail.guide.msg27": "5. 응시 중에는 새로고침(F5), 뒤로가기 버튼을 사용할 수 없습니다.",
  "inAir.layerPopEMail.guide.msg28": "6. 모바일 환경에서는 응시할 수 없습니다.",
  "inAir.layerPopEMail.guide.msg29": "7. 내용 캡쳐 및 동영상 촬영시 법적 책임을 물을 수 있습니다.",
  "inAir.layerPopEMail.label.receive_address": "받는주소",
  "inAir.layerPopEMail.label.email": "이메일 (예시:user@email.com)",
  "inAir.layerPopEMail.guide.msg30": "안내 메일 발송이 완료되었습니다.",
  "inAir.layerPopEMail.error.msg1": "안내메일 발송 실패",
  "inAir.layerPopEMail.guide.msg31": "메일이 발송되었습니다.",
  "inAir.layerPopEMail.error.msg2": "메일 발송을 실패했습니다. 다시 시도해주시기 바랍니다.",
  "inAir.layerPopEMail.label.total": "총",
  "inAir.layerPopEMail.guide.msg32": "명 (100명까지만 화면에 표시됩니다.)",
  "inAir.layerPopEMail.error.msg3":"등록된 SMS 발신번호가 존재하지 않습니다. [환경설정]에서 SMS 발신번호를 등록하신 후 진행하시기 바랍니다.",
  "inAir.layerPopEMail.label.sms_preTest": "안내 SMS 사전테스트",
  "inAir.layerPopEMail.label.send": "발송",
  "inAir.layerPopEMail.label.cellphone_example": "휴대전화번호(예시:010-0000-0000)",
  "inAir.layerPopEMail.label.recevie_phone_number": "받는번호",
  "inAir.layerPopEMail.guide.msg33": "안내 SMS 발송이 완료되었습니다.",
  "inAir.layerPopEMail.error.msg4": "안내 SMS 발송 실패",
  "inAir.layerPopEMail.guide.msg34": "SMS가 발송되었습니다.",
  "inAir.layerPopEMail.error.msg5": "SMS 발송을 실패했습니다. 다시 시도해주시기 바랍니다.",
  "inAir.sessionTimer.title": "자동로그아웃 안내",
  "inAir.sessionTimer.label.login_postphone": "로그인 연장",
  "inAir.sessionTimer.guide.msg1":"지원자 정보의 안전한 보호를 위해<br/>로그인 후 <strong>약 70분</strong> 동안 서비스 이용이 없어 <b style=\"color:#e23250\">로그아웃</b> 됩니다.",
  "inAir.sessionTimer.label.left_time": "자동 로그아웃 남은 시간",
  "inAir.sessionTimer.label.second": "초",
  "inAir.sessionTimer.alger.msg1": "로그인 시간을 연장하시겠습니까?",
  "inAir.sessionTimer.label.re_login": "다시 로그인",
  "inAir.sessionTimer.guide.msg2":"지원자 정보의 안전한 보호를 위해<br/>로그인 후 <strong>약 70분</strong> 동안 서비스 이용이 없어<br/><b style=\"color:#e23250\">자동 로그아웃</b> 되었습니다."
};
